accapp/urls.py
from django.urls import path
from .views import *

app_name = "accapp"
urlpatterns = [
    # customer urls ------------------------------------------
    path("customer/profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("customer/profile-update/", CustomerProfileUpdateView.as_view(),
         name="customerprofileupdate"),
    path("customer/password-change/", CustomerPasswordChangeView.as_view(),
         name="customerpasswordchange"),

    # branch urls --------------------------------------------------

    path("logistics/get-cities/", LogisticsGetCitiesView.as_view(),
         name="logisticsgetcities"),
    path("logistics/pickup-coverage/",
         LogisticsPickupCoverageView.as_view(), name="logisticspickupcoverage"),

    # operators management
    path("logistics/branch-list/",
         LogisticsBranchListView.as_view(), name="logisticsbranchlist"),
    path("logistics/branch-create/",
         LogisticsBranchCreateView.as_view(), name="logisticsbranchcreate"),
    path("logistics/operators/",
         LogisticsOperatorListView.as_view(), name="logisticsoperatorlist"),
    path("logistics/operators-create/",
         LogisticsOperatorCreateView.as_view(), name="logisticsoperatorcreate"),
    path("logistics/operators-<int:pk>-detail/",
         LogisticsOperatorDetailView.as_view(), name="logisticsoperatordetail"),
    path("logistics/operators-<int:pk>-update/",
         LogisticsOperatorUpdateView.as_view(), name="logisticsoperatorupdate"),
    path("logistics/operators-<int:pk>-password-change/",
         LogisticsOperatorPasswordChangeView.as_view(), name="logisticsoperatorpasswordchange"),

    # delivery persons
    path("logistics/delivery-persons/", LogisticsDeliveryPersonListView.as_view(),
         name="logisticsdeliverypersonlist"),
    path("logistics/delivery-persons-create/", LogisticsDeliveryPersonCreateView.as_view(),
         name="logisticsdeliverypersoncreate"),
    path("logistics/delivery-persons-<int:pk>-detail/", LogisticsDeliveryPersonDetailView.as_view(),
         name="logisticsdeliverypersondetail"),
    path("logistics/delivery-persons-<int:pk>-update/", LogisticsDeliveryPersonUpdateView.as_view(),
         name="logisticsdeliverypersonupdate"),
    path("logistics/delivery-persons-<int:pk>-password-change/", LogisticsDeliveryPersonPasswordChangeView.as_view(),
         name="logisticsdeliverypersonpasswordchange"),

    path("logistics/delivery-persons/attendances/", 
        LogisticsDeliveryPersonAttendanceView.as_view(), name="logisticsdeliverypersonattendance"),

    path("logistics/delivery-persons/checkin/",
         LogisticsDeliveryPersonCheckinView.as_view(), name="logisticsdeliverypersoncheckin"),

    # customer management
    path("logistics/customer-list/", LogisticsCustomerListView.as_view(),
         name="logisticscustomerlist"),
    path("logistics/customer-<int:pk>-detail/",
         LogisticsCustomerDetailView.as_view(), name="logisticscustomerdetail"),

]

lbcapp/urls.py
from django.urls import path
from .views import *

app_name = "lbcapp"
urlpatterns = [
    # customer urls ------------------------------------------------------
    # payment receiving urls
    path("customer/payment-accounts/", CustomerPaymentAccountListView.as_view(),
         name="customerpaymentaccountlist"),
    # connections
    path("customer/marketplace/", CustomerMarketplaceView.as_view(),
         name="customermarketplace"),
    path("customer/logistics-branch-<branch_id>/", CustomerLogisticsBranchDetailView.as_view(),
         name="customerlogisticsbranchdetail"),
    path("customer/connected-logistics/", CustomerConnectedLogisticsListView.as_view(),
         name="customerconnectedlogisticslist"),
    path("customer/connected-logistics-<branch_id>/", CustomerConnectedLogisticsDetailView.as_view(),
         name="customerconnectedlogisticsdetail"),

    # notices and support ticket
    path("customer/notices/", CustomerNoticeListView.as_view(),
         name="customernoticelist"),
    path("customer/support-ticekts/", CustomerSupportTicketListView.as_view(),
         name="customersupportticketlist"),
    path("customer/support-ticekts-<int:pk>/", CustomerSupportTicketDetailView.as_view(),
         name="customersupportticketdetail"),
    path("customer/support-ticekts-create/", CustomerSupportTicketCreateView.as_view(),
         name="customersupportticketcreate"),

    # branch urls ----------------------------------------------------------

    # shipping zone
    path("logistics/shipping-zones/", LogisticsShippingZoneListView.as_view(),
         name="logisticsshippingzonelist"),
    path("logistics/shipping-zones-<int:pk>/", LogisticsShippingZoneDetailView.as_view(),
         name="logisticsshippingzonedetail"),
    path("logistics/shipping-zones-create/", LogisticsShippingZoneCreateView.as_view(),
         name="logisticsshippingzonecreate"),
    path("logistics/shipping-zones-<int:pk>-update/", LogisticsShippingZoneUpdateView.as_view(),
         name="logisticsshippingzoneupdate"),
    path("logistics/sz-<sz_id>-dt-<dt_id>-szdt-create/", LogisticsSZDTCreateView.as_view(),
         name="logisticsszdtcreate"),
    path("logistics/szdt-<int:pk>-update/", LogisticsSZDTUpdateView.as_view(),
         name="logisticsszdtupdate"),

    # notices and support ticket
    path("logistics/notice-list/", LogisticsNoticeListView.as_view(),
         name="logisticsnoticelist"),
    path("logistics/notice-create/", LogisticsNoticeCreateView.as_view(),
         name="logisticsnoticecreate"),
    path("logistics/notice-<int:pk>-update/", LogisticsNoticeUpdateView.as_view(),
         name="logisticsnoticeupdate"),

    path("logistics/customer-ticket-list/", LogisticsCustomerTicketListView.as_view(),
         name="logisticscustomerticketlist"),
    path("logistics/customer-ticket-<int:pk>-detail/", LogisticsCustomerTicketDetailView.as_view(),
         name="logisticscustomerticketdetail"),
    path("logistics/customer-ticket-<int:pk>-change/", LogisticsCustomerTicketChangeView.as_view(),
         name="logisticscustomerticketchange"),

    # marketplace
    path("logistics/marketplace/", LogisticsMarketplaceView.as_view(),
         name="logisticsmarketplace"),
    path("logistics/logistics-branch-<branch_id>/", LogisticsBranchDetailView.as_view(),
         name="logisticsbranchdetail"),
    path("logistics/quotation-list/", LogisticsQuotationListView.as_view(),
         name="logisticsquotationlist"),
    path("logistics/quotation-<int:pk>-detail/",
         LogisticsQuotationDetailView.as_view(), name="logisticsquotationdetail"),
    path("logistics/connected-logistics/", LogisticsConnectedBranchListView.as_view(),
         name="logisticsconnectedbranchlist"),
    path("logistics/connected-logistics-<contract_id>/", LogisticsConnectedBranchDetailView.as_view(),
         name="logisticsconnectedbranchdetail"),


]

lmsproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("accapp.urls")),
    path('', include("lbcapp.urls")),
    path('', include("lmsapp.urls")),
    path('', include("siteapp.urls")),
    path('api/v1/rider/', include("restriderapi.urls")),
    path('api/v1/customer/', include("restcustomerapi.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/logisticstemplates/extra/logisticscustomerticketdetail.html
{% extends 'logisticstemplates/logisticsbase.html' %}
{% load static %}

{% block title %}Ticket to {{ticket.raised_by}} {% endblock %}
{% block logisticscustomertickets %}active{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
<div class="row grouped-multiple-statistics-card">
    <div class="col-md-6">
        <div id="with-header" class="card" bis_skin_checked="1">
            <div class="card-header" bis_skin_checked="1">
                <h4 class="card-title">Ticket Details</h4>
                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                <div class="heading-elements" bis_skin_checked="1">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="fa fa-minus"></i></a></li>
                        <li><a data-action="reload"><i class="fa fa-repeat"></i></a></li>
                        <li><a data-action="close"><i class="fa fa-times"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-content collapse show" bis_skin_checked="1">
                <div class="card-body border-top-blue-grey border-top-lighten-5 " bis_skin_checked="1">
                    <div class="row">
                        <div class="col-md-6">
                            {% if ticket.ticket_status == "Open" %}
                            <a href="" data-action="reviewing" class="btn btn-success ticket-status-change">Start Reviewing</a>
                            {% elif ticket.ticket_status == "Reviewing"%}
                            <a href="" data-action="solved" class="btn btn-success ticket-status-change">Make Solved</a>
                            {% else %}
                            <h5 class="text-success font-weight-bold">Ticket already solved.</h5>
                            {% endif %}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        
                        <div class="col-md-6">
                            <h5 class="font-weight-bold">Ticket Raised By</h5>
                            <p>{{ticket.raised_by}}</p>
                        </div>
                        <div class="col-md-6">
                            <h5 class="font-weight-bold">Ticket ID</h5>
                            <p>#{{ticket.id}}</p>
                        </div>
                        
                        <div class="col-md-6">
                            <h5 class="font-weight-bold">Ticket Status</h5>
                            <p>
                                {% if ticket.ticket_status == "Solved" %}
                                <span class="badge badge-success">Ticket Solved</span>
                                {% elif ticket.ticket_status == "Reviewing" %}
                                <span class="badge badge-info">Ticket Reviewing</span>
                                {% else %}
                                <span class="badge badge-primary">Ticket {{ticket.ticket_status|title}}</span>
                                {% endif %}
                            </p>
                        </div>
                        <div class="col-md-6">
                            <h5 class="font-weight-bold">Raised On</h5>
                            <p>{{ticket.created_at}}</p>
                        </div>
                        <div class="col-md-12">
                            <h5 class="font-weight-bold">Attached File</h5>
                            <p>{% if ticket.related_file %}<a href="{{ticket.related_file.url}}" target="_blank">View
                                    File</a>{% else %}No file attached{% endif %}</p>
                        </div>
                        <div class="col-md-12">
                            <h5 class="font-weight-bold">Issue Detail</h5>
                            <p>{{ticket.issue_detail|safe}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Followup Conversations</h4>
            </div>
            <div class="card-content">
                <div class="card-body border-top-blue-grey border-top-lighten-5 ">
                    <div class="row" style="height: 50vh; overflow-y: scroll;display: flex;flex-direction: column-reverse;">
                        <div>

                            {% for followup in ticket.customerticketfollowup_set.all %}
                            <div class="col-md-8 {% if followup.followup_by == logged_in_operator.logistics_branch %}ml-auto bg-success{% else %}mr-auto bg-info{% endif %} mb-1 rounded">
                                <span style="font-size: 12px;">{{followup.followup_message}}</span><br>
                                <small class="font-weight-bold">{{followup.created_at}}</small>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <form action="" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-9">
                                        <textarea placeholder="Write your reply..." name="followup_message" id="" cols="30" rows="3" class="form-control" required></textarea>
                                    </div>
                                    <div class="col-md-3">
                                        <button class="btn btn-info">Send Your Message</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

{% block js %}
<script>
    $(".ticket-status-change").on("click", function (e){
        e.preventDefault();
        var action = $(this).data("action")
        $.ajax({
            url: "{% url 'lbcapp:logisticscustomerticketchange' ticket.id %}",
            method: "post",
            data: {
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: action
            }, 
            success: function (resp) {
                if(resp.status == "success"){
                    toastr.success("Change Successful", resp.message, { showMethod: "fadeIn", hideMethod: "fadeOut", timeOut: 2e3 });
                }else{
                    toastr.error("Change unsuccessful", resp.message, { showMethod: "fadeIn", hideMethod: "fadeOut", timeOut: 2e3 });
                }
                setTimeout(function () {
                    location.href=""
                }, 500)
            }
        })
    })
</script>
{% endblock %}

templates/logisticstemplates/extra/logisticscustomerticketlist.html
{% extends 'logisticstemplates/logisticsbase.html' %}
{% load static %}

{% block title %}Customer Support tickets {% endblock %}
{% block logisticscustomertickets %}active{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<section class="users-list-wrapper">
    <div class="users-list-filter px-1">
        <div class="row border border-light rounded py-2 mb-2">
            <div class="col-md-3">
                <a href="?status=open">
                    <h5 class="text-center">Open Tickets Raised</h5>
                    <h4 class="text-center">{{open_ticket_list.count}}</h4>
                </a>
            </div>
            <div class="col-md-3">
                <a href="?status=reviewing">
                    <h5 class="text-center">Reviewing Tickets</h5>
                    <h4 class="text-center">{{reviewing_ticket_list.count}}</h4>
                </a>
            </div>
            <div class="col-md-3">
                <a href="?status=solved">
                    <h5 class="text-center">Solved Tickets</h5>
                    <h4 class="text-center">{{solved_ticket_list.count}}</h4>
                </a>
            </div>
            <div class="col-md-3">
                <a href="?status=all">
                    <h5 class="text-center">All Tickets</h5>
                    <h4 class="text-center">{{all_ticket_list.count}}</h4>
                </a>
            </div>
        </div>
    </div>
    <div class="users-list-table">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <h5>{{status|title}} Tickets</h5>
                        </div>
                        <div class="col-md-3">
                            <form action="">
                                <input type="search" name="search" class="form-control"
                                    placeholder="Type keyword & press Enter">
                            </form>
                        </div>
                    </div>
                    <!-- datatable start -->
                    <div class="table-responsive mt-1">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Ticket ID</th>
                                    <th>Raised By</th>
                                    <th>Raised Date</th>
                                    <th>Ticket Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ticket in ticket_list %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td><a href="{% url 'lbcapp:logisticscustomerticketdetail' ticket.id %}">#TKT_{{ticket.id}}</a></td>
                                    <td>
                                        {{ticket.raised_by}}
                                        {% if ticket.raised_by.company_name %}
                                        <br>({{ticket.raised_by.company_name}})
                                        {% endif %}
                                    </td>
                                    <td>{{ticket.created_at}}</td>
                                    <td><span class="font-weight-bold badge badge-{% if ticket.ticket_status == 'Solved' %}success{% elif ticket.ticket_status == 'Reviewing' %}info{% else %}warning{% endif %}">{{ticket.ticket_status}}</span></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <nav aria-label="Page navigation">
                            <p>Showing {{ticket_list.count}} of {{page_obj.paginator.count}} data</p>
                            <ul class="pagination justify-content-end">

                                <li class="page-item {% if page_obj.has_previous %}{% else %}disabled{% endif %}">
                                    <a class="page-link"
                                        href="{% if page_obj.has_previous %}?page={{page_obj.previous_page_number}}{% if request.GET.status %}&status={{request.GET.status}}{% elif request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}"
                                        tabindex="-1">Previous</a>
                                </li>

                                {% for n in page_obj.paginator.page_range %}
                                <li class="page-item {% if page_obj.number == n %}active{% endif %}"><a
                                        class="page-link"
                                        href="{% if page_obj.number == n %}#{% else %}?page={{n}}{% if request.GET.status %}&status={{request.GET.status}}{% elif request.GET.search %}&search={{request.GET.search}}{% endif %}{% endif %}">{{n}}</a>
                                </li>
                                {% endfor %}
                                <li class="page-item {% if page_obj.has_next %}{% else %}disabled{% endif %}">
                                    <a class="page-link"
                                        href="{% if page_obj.has_next %}?page={{page_obj.next_page_number}}{% if request.GET.status %}&status={{request.GET.status}}{% elif request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}">Next</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}

{% endblock %}

templates/logisticstemplates/extra/logisticsnoticecreate.html
{% extends 'logisticstemplates/logisticsbase.html' %}

{% block title %}Notice Create{% endblock %}
{% block logisticsnotices %}active{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<section class="users-edit">
    <div class="card">
        <div class="card-content">
            <div class="card-body">
                <div class="">
                    <!-- users edit media object start -->
                    <div class="media mb-2">
                        <div class="media-body">
                            <h4 class="media-heading"><strong>Create New Notice: </strong></h4>
                            <hr>
                            <span class="text-danger">Fields marked with * are required fields.</span>
                        </div>
                    </div>
                    <hr>
                    <!-- users edit media object ends -->
                    <!-- users edit account form start -->
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-12 col-sm-12">
                                        <div class="form-group">
                                            <label>Notice Title<span class="text-danger">*</span></label>
                                            {{notice_form.title}}
                                            {{notice_form.title.errors}}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-sm-12">
                                        <div class="form-group">
                                            <label>Description<span class="text-danger">*</span></label>
                                            {{notice_form.notice}}
                                            {{notice_form.notice.errors}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-8 d-flex flex-sm-row flex-column justify-content-end mt-1">
                                <button type="submit"
                                    class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1 submit-btn">Save Information</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block js %}


{% endblock %}

templates/logisticstemplates/extra/logisticsnoticelist.html
{% extends 'logisticstemplates/logisticsbase.html' %}
{% load static %}

{% block title %}Notices from you{% endblock %}

{% block logisticsnotices %}active{% endblock %}
{% block css %}

{% endblock %}

{% block content %}
<section>
    <div class="row">
        <div class="col-lg-12 col-xl-12 col-md-12">
            <div class="mb-2 mt-2">
                <h5 class="mb-0 text-uppercase d-inline">Recent Notices</h5>
                <a href="{% url 'lbcapp:logisticsnoticecreate' %}" class="btn btn-info d-inline" style="float: right;">Add new Notice</a>
                <p>All notices from you to your customers</p>
            </div>
            <div id="accordionWrap1" role="tablist" aria-multiselectable="true">
                <div class="card accordion collapse-icon accordion-icon-rotate">
                    {% for notice in notice_list %}
                    <div id="heading1{{forloop.counter}}" class="card-header primary" data-toggle="collapse"
                        href="#accordion1{{forloop.counter}}"
                        aria-expanded="{% if forloop.counter == 1 %}true{% endif %}"
                        aria-controls="accordion1{{forloop.counter}}">
                        <a class="card-title lead" href="#">{{forloop.counter}}. BY: {{notice.logistics_branch}} ({{notice.created_at}} | <span class="text-danger">{{notice.created_at|timesince}} ago</span>)</a>
                    </div>
                    <div id="accordion1{{forloop.counter}}" role="tabpanel" data-parent="#accordionWrap1"
                        aria-labelledby="heading1{{forloop.counter}}"
                        class="collapse {% if forloop.counter == 1 %}show{% endif %}">
                        <div class="card-content">
                            <div class="card-body">
                                <h4 class="card-head">{{notice.title}}</h4>
                                {{notice.notice|safe}}
                                <hr>
                                <a href="{% url 'lbcapp:logisticsnoticeupdate' notice.id %}" class="btn btn-warning">Update Notice</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <nav aria-label="Page navigation">
                <p>Showing {{notice_list.count}} of {{page_obj.paginator.count}} notices</p>
                <ul class="pagination justify-content-end">

                    <li class="page-item {% if page_obj.has_previous %}{% else %}disabled{% endif %}">
                        <a class="page-link"
                            href="{% if page_obj.has_previous %}?page={{page_obj.previous_page_number}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}"
                            tabindex="-1">Previous</a>
                    </li>

                    {% for n in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_obj.number == n %}active{% endif %}"><a
                            class="page-link"
                            href="{% if page_obj.number == n %}#{% else %}?page={{n}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}{% endif %}">{{n}}</a>
                    </li>
                    {% endfor %}
                    <li class="page-item {% if page_obj.has_next %}{% else %}disabled{% endif %}">
                        <a class="page-link"
                            href="{% if page_obj.has_next %}?page={{page_obj.next_page_number}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}

{% endblock %}