accapp/urls.py
from django.urls import path
from .views import *

app_name = "accapp"
urlpatterns = [
    # customer urls ------------------------------------------
    path("customer/profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("customer/profile-update/", CustomerProfileUpdateView.as_view(),
         name="customerprofileupdate"),
    path("customer/password-change/", CustomerPasswordChangeView.as_view(),
         name="customerpasswordchange"),

    # branch urls --------------------------------------------------

    path("logistics/get-cities/", LogisticsGetCitiesView.as_view(),
         name="logisticsgetcities"),
    path("logistics/pickup-coverage/",
         LogisticsPickupCoverageView.as_view(), name="logisticspickupcoverage"),

    # operators management
    path("logistics/branch-list/",
         LogisticsBranchListView.as_view(), name="logisticsbranchlist"),
    path("logistics/branch-create/",
         LogisticsBranchCreateView.as_view(), name="logisticsbranchcreate"),
    path("logistics/operators/",
         LogisticsOperatorListView.as_view(), name="logisticsoperatorlist"),
    path("logistics/operators-create/",
         LogisticsOperatorCreateView.as_view(), name="logisticsoperatorcreate"),
    path("logistics/operators-<int:pk>-detail/",
         LogisticsOperatorDetailView.as_view(), name="logisticsoperatordetail"),
    path("logistics/operators-<int:pk>-update/",
         LogisticsOperatorUpdateView.as_view(), name="logisticsoperatorupdate"),
    path("logistics/operators-<int:pk>-password-change/",
         LogisticsOperatorPasswordChangeView.as_view(), name="logisticsoperatorpasswordchange"),

    # delivery persons
    path("logistics/delivery-persons/", LogisticsDeliveryPersonListView.as_view(),
         name="logisticsdeliverypersonlist"),
    path("logistics/delivery-persons-create/", LogisticsDeliveryPersonCreateView.as_view(),
         name="logisticsdeliverypersoncreate"),
    path("logistics/delivery-persons-<int:pk>-detail/", LogisticsDeliveryPersonDetailView.as_view(),
         name="logisticsdeliverypersondetail"),
    path("logistics/delivery-persons-<int:pk>-update/", LogisticsDeliveryPersonUpdateView.as_view(),
         name="logisticsdeliverypersonupdate"),
    path("logistics/delivery-persons-<int:pk>-password-change/", LogisticsDeliveryPersonPasswordChangeView.as_view(),
         name="logisticsdeliverypersonpasswordchange"),

    path("logistics/delivery-persons/attendances/", 
        LogisticsDeliveryPersonAttendanceView.as_view(), name="logisticsdeliverypersonattendance"),

    path("logistics/delivery-persons/checkin/",
         LogisticsDeliveryPersonCheckinView.as_view(), name="logisticsdeliverypersoncheckin"),

    # customer management
    path("logistics/customer-list/", LogisticsCustomerListView.as_view(),
         name="logisticscustomerlist"),
    path("logistics/customer-<int:pk>-detail/",
         LogisticsCustomerDetailView.as_view(), name="logisticscustomerdetail"),

]

lmsapp/urls.py
from django.urls import path
from .views import *

app_name = "lmsapp"
urlpatterns = [
    # customer urls ----------------------------------------------------------
    # customer urls ----------------------------------------------------------
    # customer urls ----------------------------------------------------------
    # general
    path("customer/", CustomerLoginView.as_view(), name="customerlogin"),
    path("customer/logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path('customer/forgot-password/', CustomerForgotPasswordView.as_view(),
         name="customerforgotpassword"),
    path('customer/reset-password/<uidb64>/<token>/', CustomerPasswordResetView.as_view(),
         name="customerpasswordreset"),
    path('customer/reset-password/successful/', CustomerPasswordResetCompleteView.as_view(),
         name='customerpasswordresetcomplete'),
    path("customer/dashboard/", CustomerDashboardView.as_view(),
         name="customerdashboard"),
    path("customer/dashboard-ajax/",
         CustomerDashboardAjaxView.as_view(), name="customerdashboardajax"),
    path("customer/signup/", CustomerSignupView.as_view(), name="customersignup"),


    # shipment
    path("customer/shipment-list/", CustomerShipmentListView.as_view(),
         name="customershipmentlist"),
    path("customer/shipment-create/", CustomerShipmentCreateView.as_view(),
         name="customershipmentcreate"),
    path("customer/ajax-get-szs/", CustomerAjaxGetSZSView.as_view(),
         name="customerajaxgetszs"),
    path("customer/bulk-shipment/",
         CustomerBulkShipmentView.as_view(), name="customerbulkshipmentcreate"),
    path("customer/bulk-shipment/create", AjaxCustomerBulkUploadShipmentView.as_view(),
         name="ajaxcustomerbulkshipmentupload"),
    path("customer/shipment-<tracking_code>-detail/",
         CustomerShipmentDetailView.as_view(), name="customershipmentdetail"),
    path("customer/shipment-<tracking_code>-action/",
         CustomerShipmentActionView.as_view(), name="customershipmentaction"),

    # payment
    path("customer/payment-request-list/",
         CustomerPaymentRequestListView.as_view(), name="customerpaymentrequestlist"),
    path("customer/payment-request-create/",
         CustomerPaymentRequestCreateView.as_view(), name="customerpaymentrequestcreate"),
    path("customer/payment-list/", CustomerPaymentListView.as_view(),
         name="customerpaymentlist"),
    path("customer/payment-<int:pk>-detail/",
         CustomerPaymentDetailView.as_view(), name="customerpaymentdetail"),

    # notification click and redirect
    path("customer/notifications/",
         CustomerNotificationListView.as_view(), name="customernotificationlist"),
    path("customer/notifications-<int:pk>-click/",
         CustomerNotificationClickView.as_view(), name="customernotificationclick"),

    # branch urls ------------------------------------------------------------
    # branch urls ------------------------------------------------------------
    # branch urls ------------------------------------------------------------

    path("logistics/", LogisticsLoginView.as_view(), name="logisticslogin"),
    path("logistics/logout/", LogisticsLogoutView.as_view(), name="logisticslogout"),
    path("logistics/dashboard/", LogisticsDashboardView.as_view(),
         name="logisticsdashboard"),
    path("logistics/dashboard-ajax/",
         LogisticsDashboardAjaxView.as_view(), name="logisticsdashboardajax"),

    # shipment management
    path("logistics/shipment-list/",
         LogisticsShipmentListView.as_view(), name="logisticsshipmentlist"),
    path("logistics/ajax/verify-shipment-list-selection/",
         AjaxLogisticsShipmentListVerifyView.as_view(), name="ajaxlogisticsshipmentlistverify"),
    path("logistics/shipment-create/",
         LogisticsShipmentCreateView.as_view(), name="logisticsshipmentcreate"),
    path("logistics/shipment/ajax-get-szs/", LogisticsAjaxGetSZSView.as_view(),
         name="logisticsajaxgetszs"),
    path("logistics/shipment-list-table/",
         LogisticsShipmentListTableView.as_view(), name="logisticsshipmentlisttable"),
    path("logistics/customer-<int:pk>/shipment-list/",
         LogisticsCustomerShipmentListView.as_view(), name="logisticscustomershipmentlist"),
    path("logistics/shipment-<tracking_code>-detail/",
         LogisticsShipmentDetailView.as_view(), name="logisticsshipmentdetail"),
    path("logistics/shipment-<tracking_code>-update/",
         LogisticsShipmentUpdateView.as_view(), name="logisticsshipmentupdate"),
    path("logistics/shipment-action/",
         LogisticsShipmentActionView.as_view(), name="logisticsshipmentaction"),
    path("logistics/shipment-to-bundle/",
         LogisticsShipmentToBundleView.as_view(), name="logisticsshipmenttobundle"),

    path("logistics/consolidations/",
         LogisticsBundleListView.as_view(), name="logisticsbundlelist"),
    path("logistics/consolidations-create/",
         LogisticsBundleCreateView.as_view(), name="logisticsbundlecreate"),
    path("logistics/consolidations-<int:pk>/",
         LogisticsBundleDetailView.as_view(), name="logisticsbundledetail"),
    path("logistics/consolidations-<int:pk>-update/",
         LogisticsBundleUpdateView.as_view(), name="logisticsbundleupdate"),
    path("logistics/bundle-<int:pk>-shipment/",
         LogisticsBundleShipmentView.as_view(), name="logisticsbundleshipment"),
    path("logistics/custom-shipment-list/",
         LogisticsCustomShipmentListView.as_view(), name="logisticscustomshipmentlist"),
    path("logistics/ajax/custom-shipment-list/",
         AjaxLogisticsCustomShipmentListView.as_view(), name="ajaxlogisticscustomshipmentlist"),
    path("logistics/ajax/custom-shipment-table-list/",
         AjaxLogisticsCustomShipmentTableListView.as_view(), name="ajaxlogisticscustomshipmenttablelist"),

    # Logistics Customer Shipment Reports
    path("logistics/reports/customer-<int:pk>/shipmment/",
         LogisticsCustomerShipmentReportView.as_view(), name="logisticscustomershipmentreport"),

    # delivery tasks
    path("logistics/delivery-tasks/",
         LogisticsDeliveryTaskListView.as_view(), name="logisticsdeliverytasklist"),
    path("logistics/delivery-task-<int:pk>/",
         LogisticsDeliveryTaskDetailView.as_view(), name="logisticsdeliverytaskdetail"),

    # shipment label
    path('logistics/shipment-<tracking_code>/shipping-label/',
         LogisticsShipmentLabelView.as_view(), name='logisticsshippinglabel'),
    path("logistics/shipment/bulk-shipping-label/",
         LogisticsBulkShippingLabelView.as_view(), name="logisticsbulkshippinglabel"),

    # payment management
    path("logistics/customer-payment-requests/",
         LogisticsCustomerPaymentRequestListView.as_view(), name="logisticscustomerpaymentrequestlist"),
    path("logistics/customer-payment-request-<int:pk>/",
         LogisticsCustomerPaymentRequestDetailView.as_view(), name="logisticscustomerpaymentrequestdetail"),
    path("logistics/cpr-<int:pk>-pay/",
         LogisticsCustomerPaymentRequestPayView.as_view(), name="logisticscustomerpaymentrequestpay"),
    path("logistics/connected-logistics/payment-list/",
         LogisticsConnectedLogisticsPaymentListView.as_view(), name="logisticsconnectedlogisticspaymentlist"),
    path("logistics/connected-logistics/make-payment/<int:pk>/<logisticscompany>/",
         LogisticsConnectedLogisticsMakePaymentView.as_view(), name="logisticsconnectedpayment"),
    path("logistics/payment-request-create/",
         LogisticsPaymentRequestCreateView.as_view(), name="logisticspaymentrequestcreate"),
    path("logistics/logistics-payment/prequest-<int:pk>/pto-<int:pk1>/",
         LogisticsLogisticsPaymentView.as_view(), name="logisticslogisticspayment"),
    path("logistics/logistics-payment/<int:pk>-verification/",
         LogisticsLogisticsPaymentVerificationView.as_view(), name="logisticslogisticspaymentverification"),
    path("logistics/logistics-payments/",
         LogisticsPaymentReportView.as_view(), name="logisticspaymentrepots"),
    path("logistics/logistics-payments/<int:pk>/detail/",
         LogisticsBranchPaymentDetailView.as_view(), name="logisticsbranchpaymentdetail"),

    # transaction management
    path("logistics/transaction-list/", LogisticsTransactionListView.as_view(), name="logisticstransactionlist"),
    path("logistics/transaction-create/", LogisticsTransactionCreateView.as_view(), name="logisticstransactioncreate"),

    #Reports
    path("logistics/<slug:slug>/logistics-report/", LogisticsReportView.as_view(), name="logisticsreport"),

    path("logistics/overall-account-report/", 
        LogisticsOverallAccountReportView.as_view(), name="logisticsoverallaccountreport"),

     
    #Customer Wallet
    path("logistics/customer/wallet/", LogisticsCustomerWalletListView.as_view(), name="logisticscustomerwalletlist"),
 

]

lmsproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("accapp.urls")),
    path('', include("lbcapp.urls")),
    path('', include("lmsapp.urls")),
    path('', include("siteapp.urls")),
    path('api/v1/rider/', include("restriderapi.urls")),
    path('api/v1/customer/', include("restcustomerapi.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/logisticstemplates/user/logisticscustomerlist.html
{% extends 'logisticstemplates/logisticsbase.html' %}
{% load static %}

{% block title %}Customer List{% endblock %}
{% block logisticscustomers %}active{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<section class="users-list-wrapper">

    <div class="users-list-table">
        <div class="card">
            <div class="card-content">
                <div class="card-header">
                    <h4 class="card-title d-inline">Customer List</h4>
                    <a href="{% url 'accapp:logisticsdeliverypersoncreate' %}"
                        class="pull-right btn btn-info lbdt-btn d-inline" data-action="create">Add New Customer</a>
                </div>
                <hr>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <h5>Customer List ({{page_obj.paginator.count}})</h5>
                        </div>
                        <div class="col-md-3">
                            <form action="">
                                <input type="search" name="search" class="form-control"
                                    placeholder="Type keyword & press Enter">
                            </form>
                        </div>
                    </div>
                    <div class="table-responsive mt-1">
                        <table id="users-list-datatable" class="table">
                            <thead>
                                <tr>
                                    <th>Customer</th>
                                    <th>Location</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Created at</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for customer in customers %}
                                <tr>
                                    <td>
                                        <a
                                            href="{% url 'accapp:logisticscustomerdetail' customer.id %}">{{customer.full_name}}</a>
                                        {% if customer.company_name %} <br>                                        {{customer.company_name}}
                                        {% endif %}
                                    </td>
                                    <td>{{customer.city}}</td>
                                    <td>{{customer.user.username}}</td>
                                    <td>{{customer.contact_number}}</td>
                                    <td>{{customer.created_at|date}}</td>
                                    <td>

                                        <a href="{% url 'lmsapp:logisticscustomershipmentlist' customer.id %}">shipments</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <nav aria-label="Page navigation">
                            <p>Showing {{customers.count}} of {{page_obj.paginator.count}} data</p>
                            <ul class="pagination justify-content-end">

                                <li class="page-item {% if page_obj.has_previous %}{% else %}disabled{% endif %}">
                                    <a class="page-link"
                                        href="{% if page_obj.has_previous %}?page={{page_obj.previous_page_number}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}"
                                        tabindex="-1">Previous</a>
                                </li>

                                {% for n in page_obj.paginator.page_range %}
                                <li class="page-item {% if page_obj.number == n %}active{% endif %}"><a
                                        class="page-link"
                                        href="{% if page_obj.number == n %}#{% else %}?page={{n}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}{% endif %}">{{n}}</a>
                                </li>
                                {% endfor %}
                                <li class="page-item {% if page_obj.has_next %}{% else %}disabled{% endif %}">
                                    <a class="page-link"
                                        href="{% if page_obj.has_next %}?page={{page_obj.next_page_number}}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}">Next</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}


{% endblock %}

templates/logisticstemplates/user/logisticsdeliverypersondetail.html
{% extends 'logisticstemplates/logisticsbase.html' %}

{% block deliverypersons %}active{% endblock %}
{% block title %}Delivery Person Profile{% endblock %}
{% block css %}

{% endblock %}

{% block content %}

<div class="row grouped-multiple-statistics-card">
    <div class="col-md-9">
        <div id="with-header" class="card" bis_skin_checked="1">
            <div class="card-header" bis_skin_checked="1">
                <h4 class="card-title">Delivery Person Profile : <strong>{{delivery_person.full_name}}</strong></h4>
                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
            </div>
            <div class="card-content collapse show" bis_skin_checked="1">
                <div class="card-body border-top-blue-grey border-top-lighten-5 " bis_skin_checked="1">
                    <div class="row">
                        <div class="col-md-4">
                            <h5 class="font-weight-bold">Login Email</h5>
                            <p>{{delivery_person.user.username}}</p>
                        </div>

                        <div class="col-md-4">
                            <h5 class="font-weight-bold">Contact Number</h5>
                            <p>{{delivery_person.mobile}}</p>
                        </div>
                        <div class="col-md-4">
                            <h5 class="font-weight-bold">Alternative Contact</h5>
                            <p>
                                {% if delivery_person.alt_mobile %}
                                {{delivery_person.alt_mobile}}
                                {% else %}Not Provided{% endif %}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <h5 class="font-weight-bold">Location</h5>
                            <p>{{delivery_person.address}}, {{delivery_person.city}}, {{delivery_person.city.district}}</p>
                        </div>
                        <div class="col-md-4">
                            <h5 class="font-weight-bold">Joined on</h5>
                            <p>{{delivery_person.created_at}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <h5 class="font-weight-bold">Citizenship</h5>
                            <p>
                                {% if delivery_person.document1 %}
                                <a target="_blank" href="{{delivery_person.document1.url}}">Download</a>
                                {% else %}None{% endif %}
                            </p>
                        </div>
                        <div class="col-md-4">
                            <h5 class="font-weight-bold">Driving Licence</h5>
                            <p>
                                {% if delivery_person.document2 %}
                                <a href="{{delivery_person.document2.url}}">Download</a>
                                {% else %}None{% endif %}
                            </p>
                        </div>
                        <div class="col-md-4">
                            <h5 class="font-weight-bold">Other Document</h5>
                            <p>
                                {% if delivery_person.document3 %}<a
                                    href="{{delivery_person.document3.url}}">Download</a>
                                {% else %}None{% endif %}</p>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <a href="{% url 'accapp:logisticsdeliverypersonupdate' delivery_person.id %}" class="btn btn-info btn-block">Update Delivery Person</a>
                        </div>
                        <div class="col-md-6">
                            <a href="{% url 'accapp:logisticsdeliverypersonpasswordchange' delivery_person.id %}" class="btn btn-warning btn-block">Change Password</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="card">
            <div class="card-header" bis_skin_checked="1">
                <h4 class="card-title">Profile Image</h4>
            </div>
            <div class="card-content collapse show" bis_skin_checked="1">
                <div class="card-body border-top-blue-grey border-top-lighten-5 " bis_skin_checked="1">
                    <img src="{% if delivery_person.image %}{{delivery_person.image.url}}{% else %}{% endif %}" alt=""
                        class="img-fluid">
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}

{% endblock %}

templates/logisticstemplates/user/logisticsdeliverypersonlist.html
{% extends 'logisticstemplates/logisticsbase.html' %}
{% load static %}

{% block title %}Delivery Persons{% endblock %}
{% block deliverypersons %}active{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css"
    href="{% static 'logisticsstatic/app-assets/vendors/css/tables/datatable/datatables.min.css' %}">
{% endblock %}

{% block content %}
<section class="users-list-wrapper">
    
    <div class="users-list-table">
        <div class="card">
            <div class="card-content">
                <div class="card-header">
                    <h4 class="card-title d-inline">Delivery Persons</h4>
                    <a href="{% url 'accapp:logisticsdeliverypersoncreate' %}" class="pull-right btn btn-info lbdt-btn d-inline" data-action="create">Add New Delivery Person</a>
                </div>
                <hr>
                <div class="card-body">
                    <!-- datatable start -->
                    <div class="table-responsive">
                        <table id="users-list-datatable" class="table">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Full name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Created at</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for delivery_person in delivery_persons %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td><a href="{% url 'accapp:logisticsdeliverypersondetail' delivery_person.id %}">{{delivery_person.full_name}}</a></td>
                                    <td>{{delivery_person.user.username}}</td>
                                    <td>{{delivery_person.mobile}}</td>
                                    <td>{{delivery_person.created_at}}</td>
                                    <td><span class="badge badge-info font-weight-bold">{{delivery_person.status}}</span></td>
                                    <td>
                                      
                                        <a href="{% url 'accapp:logisticsdeliverypersonupdate' delivery_person.id %}"><i class="fa fa-pencil"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
<script src="{% static 'logisticsstatic/app-assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
<script>
    $(".table").DataTable({});
</script>

{% endblock %}

templates/logisticstemplates/user/logisticsoperatorlist.html
{% extends 'logisticstemplates/logisticsbase.html' %}
{% load static %}

{% block title %}Logistics Operators{% endblock %}
{% block logisticsoperators %}active{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css"
    href="{% static 'logisticsstatic/app-assets/vendors/css/tables/datatable/datatables.min.css' %}">
{% endblock %}

{% block content %}
<section class="users-list-wrapper">
    
    <div class="users-list-table">
        <div class="card">
            <div class="card-content">
                <div class="card-header">
                    <h4 class="card-title d-inline">Logistics Operators</h4>
                    <a href="{% url 'accapp:logisticsoperatorcreate' %}" class="pull-right btn btn-info lbdt-btn d-inline" data-action="create">Add New Operators</a>
                </div>
                <hr>
                <div class="card-body">
                    <!-- datatable start -->
                    <div class="table-responsive">
                        <table id="users-list-datatable" class="table">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Full name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Created at</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for logistics_operator in logistics_operators %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td><a href="{% url 'accapp:logisticsoperatordetail' logistics_operator.id %}">{{logistics_operator.full_name}}</a></td>
                                    <td>{{logistics_operator.user.username}}</td>
                                    <td>{{logistics_operator.mobile}}</td>
                                    <td>{{logistics_operator.created_at}}</td>
                                    <td><span class="badge badge-info font-weight-bold">{{logistics_operator.status}}</span></td>
                                    <td>
                                      
                                        <a href="{% url 'accapp:logisticsoperatorupdate' logistics_operator.id %}"><i class="fa fa-pencil"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}
<script src="{% static 'logisticsstatic/app-assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
<script>
    $(".table").DataTable();
</script>

{% endblock %}