accapp/urls.py
from django.urls import path
from .views import *

app_name = "accapp"
urlpatterns = [
    # customer urls ------------------------------------------
    path("customer/profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("customer/profile-update/", CustomerProfileUpdateView.as_view(),
         name="customerprofileupdate"),
    path("customer/password-change/", CustomerPasswordChangeView.as_view(),
         name="customerpasswordchange"),

    # branch urls --------------------------------------------------

    path("logistics/get-cities/", LogisticsGetCitiesView.as_view(),
         name="logisticsgetcities"),
    path("logistics/pickup-coverage/",
         LogisticsPickupCoverageView.as_view(), name="logisticspickupcoverage"),

    # operators management
    path("logistics/branch-list/",
         LogisticsBranchListView.as_view(), name="logisticsbranchlist"),
    path("logistics/branch-create/",
         LogisticsBranchCreateView.as_view(), name="logisticsbranchcreate"),
    path("logistics/operators/",
         LogisticsOperatorListView.as_view(), name="logisticsoperatorlist"),
    path("logistics/operators-create/",
         LogisticsOperatorCreateView.as_view(), name="logisticsoperatorcreate"),
    path("logistics/operators-<int:pk>-detail/",
         LogisticsOperatorDetailView.as_view(), name="logisticsoperatordetail"),
    path("logistics/operators-<int:pk>-update/",
         LogisticsOperatorUpdateView.as_view(), name="logisticsoperatorupdate"),
    path("logistics/operators-<int:pk>-password-change/",
         LogisticsOperatorPasswordChangeView.as_view(), name="logisticsoperatorpasswordchange"),

    # delivery persons
    path("logistics/delivery-persons/", LogisticsDeliveryPersonListView.as_view(),
         name="logisticsdeliverypersonlist"),
    path("logistics/delivery-persons-create/", LogisticsDeliveryPersonCreateView.as_view(),
         name="logisticsdeliverypersoncreate"),
    path("logistics/delivery-persons-<int:pk>-detail/", LogisticsDeliveryPersonDetailView.as_view(),
         name="logisticsdeliverypersondetail"),
    path("logistics/delivery-persons-<int:pk>-update/", LogisticsDeliveryPersonUpdateView.as_view(),
         name="logisticsdeliverypersonupdate"),
    path("logistics/delivery-persons-<int:pk>-password-change/", LogisticsDeliveryPersonPasswordChangeView.as_view(),
         name="logisticsdeliverypersonpasswordchange"),

    path("logistics/delivery-persons/attendances/", 
        LogisticsDeliveryPersonAttendanceView.as_view(), name="logisticsdeliverypersonattendance"),

    path("logistics/delivery-persons/checkin/",
         LogisticsDeliveryPersonCheckinView.as_view(), name="logisticsdeliverypersoncheckin"),

    # customer management
    path("logistics/customer-list/", LogisticsCustomerListView.as_view(),
         name="logisticscustomerlist"),
    path("logistics/customer-<int:pk>-detail/",
         LogisticsCustomerDetailView.as_view(), name="logisticscustomerdetail"),

]

lbcapp/urls.py
from django.urls import path
from .views import *

app_name = "lbcapp"
urlpatterns = [
    # customer urls ------------------------------------------------------
    # payment receiving urls
    path("customer/payment-accounts/", CustomerPaymentAccountListView.as_view(),
         name="customerpaymentaccountlist"),
    # connections
    path("customer/marketplace/", CustomerMarketplaceView.as_view(),
         name="customermarketplace"),
    path("customer/logistics-branch-<branch_id>/", CustomerLogisticsBranchDetailView.as_view(),
         name="customerlogisticsbranchdetail"),
    path("customer/connected-logistics/", CustomerConnectedLogisticsListView.as_view(),
         name="customerconnectedlogisticslist"),
    path("customer/connected-logistics-<branch_id>/", CustomerConnectedLogisticsDetailView.as_view(),
         name="customerconnectedlogisticsdetail"),

    # notices and support ticket
    path("customer/notices/", CustomerNoticeListView.as_view(),
         name="customernoticelist"),
    path("customer/support-ticekts/", CustomerSupportTicketListView.as_view(),
         name="customersupportticketlist"),
    path("customer/support-ticekts-<int:pk>/", CustomerSupportTicketDetailView.as_view(),
         name="customersupportticketdetail"),
    path("customer/support-ticekts-create/", CustomerSupportTicketCreateView.as_view(),
         name="customersupportticketcreate"),

    # branch urls ----------------------------------------------------------

    # shipping zone
    path("logistics/shipping-zones/", LogisticsShippingZoneListView.as_view(),
         name="logisticsshippingzonelist"),
    path("logistics/shipping-zones-<int:pk>/", LogisticsShippingZoneDetailView.as_view(),
         name="logisticsshippingzonedetail"),
    path("logistics/shipping-zones-create/", LogisticsShippingZoneCreateView.as_view(),
         name="logisticsshippingzonecreate"),
    path("logistics/shipping-zones-<int:pk>-update/", LogisticsShippingZoneUpdateView.as_view(),
         name="logisticsshippingzoneupdate"),
    path("logistics/sz-<sz_id>-dt-<dt_id>-szdt-create/", LogisticsSZDTCreateView.as_view(),
         name="logisticsszdtcreate"),
    path("logistics/szdt-<int:pk>-update/", LogisticsSZDTUpdateView.as_view(),
         name="logisticsszdtupdate"),

    # notices and support ticket
    path("logistics/notice-list/", LogisticsNoticeListView.as_view(),
         name="logisticsnoticelist"),
    path("logistics/notice-create/", LogisticsNoticeCreateView.as_view(),
         name="logisticsnoticecreate"),
    path("logistics/notice-<int:pk>-update/", LogisticsNoticeUpdateView.as_view(),
         name="logisticsnoticeupdate"),

    path("logistics/customer-ticket-list/", LogisticsCustomerTicketListView.as_view(),
         name="logisticscustomerticketlist"),
    path("logistics/customer-ticket-<int:pk>-detail/", LogisticsCustomerTicketDetailView.as_view(),
         name="logisticscustomerticketdetail"),
    path("logistics/customer-ticket-<int:pk>-change/", LogisticsCustomerTicketChangeView.as_view(),
         name="logisticscustomerticketchange"),

    # marketplace
    path("logistics/marketplace/", LogisticsMarketplaceView.as_view(),
         name="logisticsmarketplace"),
    path("logistics/logistics-branch-<branch_id>/", LogisticsBranchDetailView.as_view(),
         name="logisticsbranchdetail"),
    path("logistics/quotation-list/", LogisticsQuotationListView.as_view(),
         name="logisticsquotationlist"),
    path("logistics/quotation-<int:pk>-detail/",
         LogisticsQuotationDetailView.as_view(), name="logisticsquotationdetail"),
    path("logistics/connected-logistics/", LogisticsConnectedBranchListView.as_view(),
         name="logisticsconnectedbranchlist"),
    path("logistics/connected-logistics-<contract_id>/", LogisticsConnectedBranchDetailView.as_view(),
         name="logisticsconnectedbranchdetail"),


]

lmsproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("accapp.urls")),
    path('', include("lbcapp.urls")),
    path('', include("lmsapp.urls")),
    path('', include("siteapp.urls")),
    path('api/v1/rider/', include("restriderapi.urls")),
    path('api/v1/customer/', include("restcustomerapi.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/logisticstemplates/setting/logisticsgetcities.html
<table class="table table-bordered" style="width: 100%;">
    <strong>Cities: ({{cities.count}} Cities)</strong>
    <tbody>
        {% for city in cities %}
        <td style="font-size: 12px;">{{city.name}} 
            {% if city not in added_cities %}
            <a href="" class="add-city" style="float:right;" data-id="{{city.id}}"><i class="fa fa-check"></i></a>
            {% endif %}
        </td>
        {% if forloop.counter|divisibleby:5 %}<tr>{% endif %}
            {% endfor %}
    </tbody>   
</table>
<hr>
<div class="row">
    <div class="col-md-6">
        <td><a class="btn btn-primary all_add_remove" data-action="all_add" href="" data-district_id="{{district.id}}">Add All</a></td>
    </div>
    <div class="col-md-6">
        <td><a class="btn btn-danger all_add_remove" data-action="all_remove" href="" data-district_id="{{district.id}}">Remove All</a></td>
    </div>
</div>

templates/logisticstemplates/setting/logisticshippingzonelist.html
{% extends 'logisticstemplates/logisticsbase.html' %}
{% load static %}

{% block logisticsshippingzones %}active{% endblock %}
{% block title %}Shipping Zones{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css"
    href="{% static 'logisticsstatic/app-assets/vendors/css/tables/datatable/datatables.min.css' %}">
{% endblock %}

{% block content %}
<section class="users-list-wrapper">
    
    <div class="users-list-table">
        <div class="card">
            <div class="card-content">
                <div class="card-header">
                    <h4 class="card-title d-inline">All Shipping Zones</h4>
                    <a href="{% url 'lbcapp:logisticsshippingzonecreate' %}" class="pull-right btn btn-info d-inline">Add New Shipping Zone</a>
                </div>
                <hr>
                <div class="card-body">
                    <!-- datatable start -->
                    <div class="table-responsive">
                        <table id="users-list-datatable" class="table">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Shipping Zone</th>
                                    <th>Delivery Types</th>
                                    <th>Cities</th>
                                    <th>Created at</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for shipping_zone in shipping_zones %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td><a href="{% url 'lbcapp:logisticsshippingzonedetail' shipping_zone.id %}">{{shipping_zone.shipping_zone}}</a></td>
                                    <td>{% for szdt in shipping_zone.shippingzonedeliverytype_set.all %}{{szdt.delivery_type.delivery_type}}{% endfor %}</td>
                                    <td>{{shipping_zone.cities.all.count}}</td>
                                    <td>{{shipping_zone.created_at}}</td>
                                    <td>
                                        <a href="{% url 'lbcapp:logisticsshippingzoneupdate' shipping_zone.id %}" ><i class="fa fa-pencil"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-content">
                <div class="card-header">
                    <h4 class="card-title d-inline">Delivery Types</h4>
                    <a href="{% url 'lbcapp:logisticsshippingzonecreate' %}" class="pull-right btn btn-info lbdt-btn d-inline" data-action="create">Add New Delivery Type</a>
                </div>
                <hr>
                <div class="card-body">
                    <!-- datatable start -->
                    <div class="table-responsive">
                        <table id="users-list-datatable" class="table">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Delivery Type</th>
                                    <th>Packages</th>
                                    <th>Created at</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for delivery_type in delivery_types %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td class="lb_dt">{{delivery_type.delivery_type}}</td>
                                    <td>{{delivery_type.shippingzonedeliverytype_set.all.count}}</td>
                                    <td>{{delivery_type.created_at}}</td>
                                    <td>
                                        {% if delivery_type.delivery_type == "Standard" or delivery_type.delivery_type == "standard" or delivery_type.delivery_type == "Standard Delivery" %}
                                        {% else %}
                                        <a class="lbdt-btn" href="" data-action="update" data-pk="{{delivery_type.id}}"><i class="fa fa-pencil"></i></a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade text-left" id="lbdt-form-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel33"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <label class="modal-title text-text-bold-600" id="myModalLabel33">Delivery Type Information</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="#" method="POST" id="lbdt-form">
                {% csrf_token %}
                <input type="hidden" name="lbdt_pk" id="lbdt_pk">
                <div class="modal-body">
                    <label>Delivery Type: <span class="text-danger">*</span></label>
                    <div class="form-group">
                        <input type="text" placeholder="Delivery type name. eg. express ..." class="form-control" id="delivery_type" name="delivery_type" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="reset" class="btn btn-outline-secondary btn-lg" data-dismiss="modal" value="close">
                    <input type="submit" class="btn btn-outline-primary btn-lg" value="Save Information">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'logisticsstatic/app-assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
<script>
    $(".table").DataTable();
</script>
<script>
    $(".lbdt-btn").on("click", function(e){
        e.preventDefault();
        var action = $(this).data("action");
        if(action == "create"){
            $('#lbdt-form-modal').modal('show')
        }else if(action == "update"){
            var pk = $(this).data("pk")
            var delivery_type = $(this).parent().parent().find(".lb_dt").text()
            $("#lbdt_pk").val(pk)
            $("#delivery_type").val(delivery_type)
            $('#lbdt-form-modal').modal('show')
        }
    })
    $('#lbdt-form-modal').on("hide.bs.modal	", function(){
        $("#lbdt-form").trigger("reset")
    })
</script>
{% endblock %}

templates/logisticstemplates/setting/logisticsshippingzonedetail.html
{% extends 'logisticstemplates/logisticsbase.html' %}

{% load static %}
{% block title %}{{shipping_zone}}{% endblock %}
{% block logisticsshippingzones %}active{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css"
    href="{% static 'customerstatic/app-assets/vendors/css/forms/selects/select2.min.css' %}">
{% endblock %}

{% block content %}
<div class="row grouped-multiple-statistics-card">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Shipping Zones: <strong>{{shipping_zone.shipping_zone}} </strong></h4>
            </div>
            <div class="card-content">
                <div class="card-body border-top-blue-grey border-top-lighten-5 " bis_skin_checked="1">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Delivery Type</th>
                                    <th>Shipping Charge</th>
                                    <th>COD Handling Charge</th>
                                    <th>Rejection Handling Charge</th>
                                    <th>Update</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for szdt in shipping_zone.shippingzonedeliverytype_set.all %}
                                {% if szdt.status == "Active" %}
                                <tr>
                                    <td>{{szdt.delivery_type.delivery_type}}</td>
                                    <td>Rs. {{szdt.shipping_charge_per_kg}}/Kg <br> (Rs.
                                        {{szdt.additional_shipping_charge_per_kg}}/Kg for additional)</td>
                                    <td>Rs. {{szdt.cod_handling_charge}}%</td>
                                    <td>Rs. {{szdt.rejection_handling_charge}}%</td>
                                    <td>
                                        <a href="{% url 'lbcapp:logisticsszdtupdate' szdt.id %}" class="btn btn-info"><i
                                                class="fa fa-pencil"></i></a>
                                    </td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                {% if unset_delivery_types %}
                <div class="card-body border-top-blue-grey border-top-lighten-5 " bis_skin_checked="1">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <h5 class="font-weight-bold">You have not set charge for these delivery types yet.</h5>
                            <tbody>
                                {% for dt in unset_delivery_types %}
                                <td>{{forloop.counter}}. {{dt.delivery_type}} | <a
                                        href="{% url 'lbcapp:logisticsszdtcreate' shipping_zone.id dt.id %}">Setup
                                        now</a></td>
                                {% if forloop.counter|divisibleby:5 %}<tr>{% endif %}
                                    {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                {% endif %}
                <div class="card-body border-top-blue-grey border-top-lighten-5 " bis_skin_checked="1">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="cities-table">
                            <h5 class="font-weight-bold">Cities in this Shipping Zone:</h5>
                            <tbody>
                                {% for city in shipping_zone.cities.all %}
                                <td title="{{city.district.name}}">{{city.name}}
                                    <i data-id="{{city.id}}" class="fa fa-times remove-city"
                                        style="float: right;color: rgb(13, 150, 181);cursor: pointer;"></i>
                                </td>
                                {% if forloop.counter|divisibleby:5 %}<tr>{% endif %}
                                    {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Add more cities in this Shipping Zone</h4>
            </div>
            <div class="card-content">
                <div class="card-body border-top-blue-grey border-top-lighten-5 " bis_skin_checked="1">
                    <div class="row">
                        <div class="col-md-6">
                            <select name="select_district" id="select_district" class="form-control select2">
                                <option value selected>Select District</option>
                                {% for district in districts %}
                                <option value="{{district.id}}">{{district.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-info">Load cities</button>
                        </div>
                        <hr>
                        <div class="col-md-12 table-responsive" id="loaded-cities">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script src="{% static 'customerstatic/app-assets/vendors/js/forms/select/select2.full.min.js' %}"></script>
<script src="{% static 'customerstatic/app-assets/js/scripts/forms/select/form-select2.min.js' %}"></script>

<script>
    $("#select_district").on("change click", function (e) {
        var district_id = $(this).val()
        if (district_id) {
            $.ajax({
                url: `{% url 'accapp:logisticsgetcities' %}?district_id=${district_id}`,
                method: "get",
                success: function (resp) {
                    $("#loaded-cities").html(resp)
                    setTimeout(function () {
                        $(".add-city").on("click", function (e) {
                            e.preventDefault();
                            var city = $(this).parent().text()
                            var city_id = $(this).data("id")
                            Swal.fire({
                                html: `Are you sure to add <span class="text-danger">${city}</span> in this shipping zone?`,
                                type: "warning",
                                showCancelButton: !0,
                                confirmButtonColor: "#3085d6",
                                cancelButtonColor: "#d33",
                                confirmButtonText: "Yes, add!",
                                confirmButtonClass: "btn btn-info",
                                cancelButtonClass: "btn btn-danger ml-1",
                                buttonsStyling: !1,
                            }).then(function (t) {
                                if (t.value == 1) {
                                    $.ajax({
                                        method: "post",
                                        data: {
                                            csrfmiddlewaretoken: "{{csrf_token}}",
                                            city_id: city_id,
                                            action: "add"
                                        },
                                        success: function (resp) {
                                            if (resp.status == "success") {
                                                // Swal.fire({ type: "success", title: "Success!", text: "City added successfully.", confirmButtonClass: "btn btn-success" });
                                                $("#cities-table").load(location.href + " #cities-table");
                                                setTimeout(function () {
                                                    $(".remove-city").on("click", function (e) {
                                                        e.preventDefault();
                                                        removeCity(e)
                                                    })
                                                }, 500)
                                            } else {
                                                Swal.fire({ type: "error", title: "Error!", text: resp.message, confirmButtonClass: "btn btn-danger" });
                                            }
                                        }
                                    })

                                }

                            });
                        })
                        $(".all_add_remove").on("click", function (e) {
                            e.preventDefault();
                            var act = $(this).data("action")
                            var btn_text = $(this).text()
                            var district_id = $(this).data("district_id")
                            Swal.fire({
                                html: `Are you sure to ${btn_text} in this shipping zone?`,
                                type: "warning",
                                showCancelButton: !0,
                                confirmButtonColor: "#3085d6",
                                cancelButtonColor: "#d33",
                                confirmButtonText: `Yes, ${btn_text}!`,
                                confirmButtonClass: "btn btn-info",
                                cancelButtonClass: "btn btn-danger ml-1",
                                buttonsStyling: !1,
                            }).then(function (t) {
                                if (t.value == 1) {
                                    $.ajax({
                                        method: "post",
                                        data: {
                                            csrfmiddlewaretoken: "{{csrf_token}}",
                                            district_id: district_id,
                                            action: act
                                        },
                                        success: function (resp) {
                                            if (resp.status == "success") {
                                                $("#cities-table").load(location.href + " #cities-table");
                                                setTimeout(function () {
                                                    $(".remove-city").on("click", function (e) {
                                                        e.preventDefault();
                                                        removeCity(e)
                                                    })
                                                }, 500)

                                            } else {
                                                Swal.fire({ type: "error", title: "Error!", text: resp.message, confirmButtonClass: "btn btn-danger" });
                                            }
                                        }
                                    })
                                }

                            })
                        })
                    }, 500)
                }
            })
        } else {
            $("#loaded-cities").html('')
        }
    })
    $(".remove-city").on("click", function (e) {
        e.preventDefault();
        removeCity(e)
    })
    function removeCity(e) {
        var city = e.target.parentElement.innerText
        var city_id = e.target.getAttribute("data-id")
        Swal.fire({
            html: `Are you sure to remove <span class="text-danger">${city}</span> from this shipping zone?`,
            type: "warning",
            showCancelButton: !0,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Yes, remove!",
            confirmButtonClass: "btn btn-info",
            cancelButtonClass: "btn btn-danger ml-1",
            buttonsStyling: !1,
        }).then(function (t) {
            if (t.value == 1) {
                $.ajax({
                    method: "post",
                    data: {
                        csrfmiddlewaretoken: "{{csrf_token}}",
                        city_id: city_id,
                        action: "remove"
                    },
                    success: function (resp) {
                        if (resp.status == "success") {
                            // Swal.fire({ type: "success", title: "Success!", text: "City removed successfully.", confirmButtonClass: "btn btn-success" });
                            $("#cities-table").load(location.href + " #cities-table");
                            setTimeout(function () {
                                $(".remove-city").on("click", function (e) {
                                    e.preventDefault();
                                    removeCity(e)
                                })
                            }, 500)

                        } else {
                            Swal.fire({ type: "error", title: "Error!", text: resp.message, confirmButtonClass: "btn btn-danger" });
                        }
                    }
                })
            }

        })
    }
</script>
{% endblock %}