accapp/urls.py
from django.urls import path
from .views import *

app_name = "accapp"
urlpatterns = [
    # customer urls ------------------------------------------
    path("customer/profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("customer/profile-update/", CustomerProfileUpdateView.as_view(),
         name="customerprofileupdate"),
    path("customer/password-change/", CustomerPasswordChangeView.as_view(),
         name="customerpasswordchange"),

    # branch urls --------------------------------------------------

    path("logistics/get-cities/", LogisticsGetCitiesView.as_view(),
         name="logisticsgetcities"),
    path("logistics/pickup-coverage/",
         LogisticsPickupCoverageView.as_view(), name="logisticspickupcoverage"),

    # operators management
    path("logistics/branch-list/",
         LogisticsBranchListView.as_view(), name="logisticsbranchlist"),
    path("logistics/branch-create/",
         LogisticsBranchCreateView.as_view(), name="logisticsbranchcreate"),
    path("logistics/operators/",
         LogisticsOperatorListView.as_view(), name="logisticsoperatorlist"),
    path("logistics/operators-create/",
         LogisticsOperatorCreateView.as_view(), name="logisticsoperatorcreate"),
    path("logistics/operators-<int:pk>-detail/",
         LogisticsOperatorDetailView.as_view(), name="logisticsoperatordetail"),
    path("logistics/operators-<int:pk>-update/",
         LogisticsOperatorUpdateView.as_view(), name="logisticsoperatorupdate"),
    path("logistics/operators-<int:pk>-password-change/",
         LogisticsOperatorPasswordChangeView.as_view(), name="logisticsoperatorpasswordchange"),

    # delivery persons
    path("logistics/delivery-persons/", LogisticsDeliveryPersonListView.as_view(),
         name="logisticsdeliverypersonlist"),
    path("logistics/delivery-persons-create/", LogisticsDeliveryPersonCreateView.as_view(),
         name="logisticsdeliverypersoncreate"),
    path("logistics/delivery-persons-<int:pk>-detail/", LogisticsDeliveryPersonDetailView.as_view(),
         name="logisticsdeliverypersondetail"),
    path("logistics/delivery-persons-<int:pk>-update/", LogisticsDeliveryPersonUpdateView.as_view(),
         name="logisticsdeliverypersonupdate"),
    path("logistics/delivery-persons-<int:pk>-password-change/", LogisticsDeliveryPersonPasswordChangeView.as_view(),
         name="logisticsdeliverypersonpasswordchange"),

    path("logistics/delivery-persons/attendances/", 
        LogisticsDeliveryPersonAttendanceView.as_view(), name="logisticsdeliverypersonattendance"),

    path("logistics/delivery-persons/checkin/",
         LogisticsDeliveryPersonCheckinView.as_view(), name="logisticsdeliverypersoncheckin"),

    # customer management
    path("logistics/customer-list/", LogisticsCustomerListView.as_view(),
         name="logisticscustomerlist"),
    path("logistics/customer-<int:pk>-detail/",
         LogisticsCustomerDetailView.as_view(), name="logisticscustomerdetail"),

]

lmsapp/urls.py
from django.urls import path
from .views import *

app_name = "lmsapp"
urlpatterns = [
    # customer urls ----------------------------------------------------------
    # customer urls ----------------------------------------------------------
    # customer urls ----------------------------------------------------------
    # general
    path("customer/", CustomerLoginView.as_view(), name="customerlogin"),
    path("customer/logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path('customer/forgot-password/', CustomerForgotPasswordView.as_view(),
         name="customerforgotpassword"),
    path('customer/reset-password/<uidb64>/<token>/', CustomerPasswordResetView.as_view(),
         name="customerpasswordreset"),
    path('customer/reset-password/successful/', CustomerPasswordResetCompleteView.as_view(),
         name='customerpasswordresetcomplete'),
    path("customer/dashboard/", CustomerDashboardView.as_view(),
         name="customerdashboard"),
    path("customer/dashboard-ajax/",
         CustomerDashboardAjaxView.as_view(), name="customerdashboardajax"),
    path("customer/signup/", CustomerSignupView.as_view(), name="customersignup"),


    # shipment
    path("customer/shipment-list/", CustomerShipmentListView.as_view(),
         name="customershipmentlist"),
    path("customer/shipment-create/", CustomerShipmentCreateView.as_view(),
         name="customershipmentcreate"),
    path("customer/ajax-get-szs/", CustomerAjaxGetSZSView.as_view(),
         name="customerajaxgetszs"),
    path("customer/bulk-shipment/",
         CustomerBulkShipmentView.as_view(), name="customerbulkshipmentcreate"),
    path("customer/bulk-shipment/create", AjaxCustomerBulkUploadShipmentView.as_view(),
         name="ajaxcustomerbulkshipmentupload"),
    path("customer/shipment-<tracking_code>-detail/",
         CustomerShipmentDetailView.as_view(), name="customershipmentdetail"),
    path("customer/shipment-<tracking_code>-action/",
         CustomerShipmentActionView.as_view(), name="customershipmentaction"),

    # payment
    path("customer/payment-request-list/",
         CustomerPaymentRequestListView.as_view(), name="customerpaymentrequestlist"),
    path("customer/payment-request-create/",
         CustomerPaymentRequestCreateView.as_view(), name="customerpaymentrequestcreate"),
    path("customer/payment-list/", CustomerPaymentListView.as_view(),
         name="customerpaymentlist"),
    path("customer/payment-<int:pk>-detail/",
         CustomerPaymentDetailView.as_view(), name="customerpaymentdetail"),

    # notification click and redirect
    path("customer/notifications/",
         CustomerNotificationListView.as_view(), name="customernotificationlist"),
    path("customer/notifications-<int:pk>-click/",
         CustomerNotificationClickView.as_view(), name="customernotificationclick"),

    # branch urls ------------------------------------------------------------
    # branch urls ------------------------------------------------------------
    # branch urls ------------------------------------------------------------

    path("logistics/", LogisticsLoginView.as_view(), name="logisticslogin"),
    path("logistics/logout/", LogisticsLogoutView.as_view(), name="logisticslogout"),
    path("logistics/dashboard/", LogisticsDashboardView.as_view(),
         name="logisticsdashboard"),
    path("logistics/dashboard-ajax/",
         LogisticsDashboardAjaxView.as_view(), name="logisticsdashboardajax"),

    # shipment management
    path("logistics/shipment-list/",
         LogisticsShipmentListView.as_view(), name="logisticsshipmentlist"),
    path("logistics/ajax/verify-shipment-list-selection/",
         AjaxLogisticsShipmentListVerifyView.as_view(), name="ajaxlogisticsshipmentlistverify"),
    path("logistics/shipment-create/",
         LogisticsShipmentCreateView.as_view(), name="logisticsshipmentcreate"),
    path("logistics/shipment/ajax-get-szs/", LogisticsAjaxGetSZSView.as_view(),
         name="logisticsajaxgetszs"),
    path("logistics/shipment-list-table/",
         LogisticsShipmentListTableView.as_view(), name="logisticsshipmentlisttable"),
    path("logistics/customer-<int:pk>/shipment-list/",
         LogisticsCustomerShipmentListView.as_view(), name="logisticscustomershipmentlist"),
    path("logistics/shipment-<tracking_code>-detail/",
         LogisticsShipmentDetailView.as_view(), name="logisticsshipmentdetail"),
    path("logistics/shipment-<tracking_code>-update/",
         LogisticsShipmentUpdateView.as_view(), name="logisticsshipmentupdate"),
    path("logistics/shipment-action/",
         LogisticsShipmentActionView.as_view(), name="logisticsshipmentaction"),
    path("logistics/shipment-to-bundle/",
         LogisticsShipmentToBundleView.as_view(), name="logisticsshipmenttobundle"),

    path("logistics/consolidations/",
         LogisticsBundleListView.as_view(), name="logisticsbundlelist"),
    path("logistics/consolidations-create/",
         LogisticsBundleCreateView.as_view(), name="logisticsbundlecreate"),
    path("logistics/consolidations-<int:pk>/",
         LogisticsBundleDetailView.as_view(), name="logisticsbundledetail"),
    path("logistics/consolidations-<int:pk>-update/",
         LogisticsBundleUpdateView.as_view(), name="logisticsbundleupdate"),
    path("logistics/bundle-<int:pk>-shipment/",
         LogisticsBundleShipmentView.as_view(), name="logisticsbundleshipment"),
    path("logistics/custom-shipment-list/",
         LogisticsCustomShipmentListView.as_view(), name="logisticscustomshipmentlist"),
    path("logistics/ajax/custom-shipment-list/",
         AjaxLogisticsCustomShipmentListView.as_view(), name="ajaxlogisticscustomshipmentlist"),
    path("logistics/ajax/custom-shipment-table-list/",
         AjaxLogisticsCustomShipmentTableListView.as_view(), name="ajaxlogisticscustomshipmenttablelist"),

    # Logistics Customer Shipment Reports
    path("logistics/reports/customer-<int:pk>/shipmment/",
         LogisticsCustomerShipmentReportView.as_view(), name="logisticscustomershipmentreport"),

    # delivery tasks
    path("logistics/delivery-tasks/",
         LogisticsDeliveryTaskListView.as_view(), name="logisticsdeliverytasklist"),
    path("logistics/delivery-task-<int:pk>/",
         LogisticsDeliveryTaskDetailView.as_view(), name="logisticsdeliverytaskdetail"),

    # shipment label
    path('logistics/shipment-<tracking_code>/shipping-label/',
         LogisticsShipmentLabelView.as_view(), name='logisticsshippinglabel'),
    path("logistics/shipment/bulk-shipping-label/",
         LogisticsBulkShippingLabelView.as_view(), name="logisticsbulkshippinglabel"),

    # payment management
    path("logistics/customer-payment-requests/",
         LogisticsCustomerPaymentRequestListView.as_view(), name="logisticscustomerpaymentrequestlist"),
    path("logistics/customer-payment-request-<int:pk>/",
         LogisticsCustomerPaymentRequestDetailView.as_view(), name="logisticscustomerpaymentrequestdetail"),
    path("logistics/cpr-<int:pk>-pay/",
         LogisticsCustomerPaymentRequestPayView.as_view(), name="logisticscustomerpaymentrequestpay"),
    path("logistics/connected-logistics/payment-list/",
         LogisticsConnectedLogisticsPaymentListView.as_view(), name="logisticsconnectedlogisticspaymentlist"),
    path("logistics/connected-logistics/make-payment/<int:pk>/<logisticscompany>/",
         LogisticsConnectedLogisticsMakePaymentView.as_view(), name="logisticsconnectedpayment"),
    path("logistics/payment-request-create/",
         LogisticsPaymentRequestCreateView.as_view(), name="logisticspaymentrequestcreate"),
    path("logistics/logistics-payment/prequest-<int:pk>/pto-<int:pk1>/",
         LogisticsLogisticsPaymentView.as_view(), name="logisticslogisticspayment"),
    path("logistics/logistics-payment/<int:pk>-verification/",
         LogisticsLogisticsPaymentVerificationView.as_view(), name="logisticslogisticspaymentverification"),
    path("logistics/logistics-payments/",
         LogisticsPaymentReportView.as_view(), name="logisticspaymentrepots"),
    path("logistics/logistics-payments/<int:pk>/detail/",
         LogisticsBranchPaymentDetailView.as_view(), name="logisticsbranchpaymentdetail"),

    # transaction management
    path("logistics/transaction-list/", LogisticsTransactionListView.as_view(), name="logisticstransactionlist"),
    path("logistics/transaction-create/", LogisticsTransactionCreateView.as_view(), name="logisticstransactioncreate"),

    #Reports
    path("logistics/<slug:slug>/logistics-report/", LogisticsReportView.as_view(), name="logisticsreport"),

    path("logistics/overall-account-report/", 
        LogisticsOverallAccountReportView.as_view(), name="logisticsoverallaccountreport"),

     
    #Customer Wallet
    path("logistics/customer/wallet/", LogisticsCustomerWalletListView.as_view(), name="logisticscustomerwalletlist"),
 

]

lmsproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("accapp.urls")),
    path('', include("lbcapp.urls")),
    path('', include("lmsapp.urls")),
    path('', include("siteapp.urls")),
    path('api/v1/rider/', include("restriderapi.urls")),
    path('api/v1/customer/', include("restcustomerapi.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/logisticstemplates/payment/logisticsconnectedlogisticspaymentlist.html
{% extends 'logisticstemplates/logisticsbase.html' %}
{% load static %}
{% load humanize %}

{% block logisticspay %}active{% endblock %}
{% block title %}Connected Logistics {% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<section class="users-list-wrapper">
    <div class="users-list-filter px-1">
        <div class="row border border-light rounded py-2 mb-2">
            <div class="col-md-3">
                <a href="?status=unsettled">
                    <h5 class="text-center">Unsettled Requests</h5>
                    <h4 class="text-center">{{unsettled_requests}}</h4>
                </a>
            </div>
            <div class="col-md-2">
                <a href="?status=verify">
                    <h5 class="text-center">Verify Payments</h5>
                    <h4 class="text-center">{{verify_requests}}</h4>
                </a>
            </div>
            <div class="col-md-2">
                <a href="?status=settled">
                    <h5 class="text-center">Settled Requests</h5>
                    <h4 class="text-center">{{settled_requests}}</h4>
                </a>
            </div>
            <div class="col-md-2">
                <a href="?status=all">
                    <h5 class="text-center">All Requests</h5>
                    <h4 class="text-center">{{payment_requests}}</h4>
                </a>
            </div>
            <div class="col-md-3">
                <a href="?status=connectedlogistics">
                    <h5 class="text-center">Connected Logistics</h5>
                    <h4 class="text-center">{{connected_logistics_count}}</h4>
                </a>
            </div>
        </div>
    </div>
    <div class="users-list-table">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <h5>{{status|title}}</h5>
                        </div>
                        <div class="col-md-3">
                            <form action="">
                                <input type="search" name="search" class="form-control"
                                    placeholder="Type keyword & press Enter">
                            </form>
                        </div>
                    </div>
                    <!-- datatable start -->
                    {% if status == 'Connected Logistics List' %}
                    <div class="table-responsive mt-1">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Connected Logistics</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for logistics in connected_logistics %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>
                                        <a href="">Company: {{logistics.logistics_company}}
                                        <br>Branch: {{logistics.branch_city}}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'lmsapp:logisticsconnectedpayment' logistics.id logistics.logistics_company %}">View</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <nav aria-label="Page navigation">
                            <p>Showing {{shipments.count}} of {{page_obj.paginator.count}} data</p>
                            <ul class="pagination justify-content-end">

                                <li class="page-item {% if page_obj.has_previous %}{% else %}disabled{% endif %}">
                                    <a class="page-link"
                                        href="{% if page_obj.has_previous %}?page={{page_obj.previous_page_number}}{% if request.GET.status %}&status={{request.GET.status}}{% elif request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}"
                                        tabindex="-1">Previous</a>
                                </li>

                                {% for n in page_obj.paginator.page_range %}
                                <li class="page-item {% if page_obj.number == n %}active{% endif %}"><a
                                        class="page-link"
                                        href="{% if page_obj.number == n %}#{% else %}?page={{n}}{% if request.GET.status %}&status={{request.GET.status}}{% elif request.GET.search %}&search={{request.GET.search}}{% endif %}{% endif %}">{{n}}</a>
                                </li>
                                {% endfor %}
                                <li class="page-item {% if page_obj.has_next %}{% else %}disabled{% endif %}">
                                    <a class="page-link"
                                        href="{% if page_obj.has_next %}?page={{page_obj.next_page_number}}{% if request.GET.status %}&status={{request.GET.status}}{% elif request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}">Next</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    {% else %}
                    <div class="table-responsive mt-1">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Request From</th>
                                    <th>Request To</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for prequest in prequests %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>
                                        <a href="#">Company: {{prequest.requested_by.logistics_company}}
                                        <br>Branch: {{prequest.requested_by.branch_city}}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="#">Company: {{prequest.requested_to.logistics_company}}
                                        <br>Branch: {{prequest.requested_to.branch_city}}
                                        </a>
                                    </td>
                                    <td>
                                        {% if prequest.is_settled == True and prequest.is_verified == False and prequest.payer_logistics != mybranch %}
                                        <a href="{% url 'lmsapp:logisticslogisticspaymentverification' prequest.id %}">Verify Payment</a>
                                        {% else %}
                                        <a href="{% url 'lmsapp:logisticslogisticspayment' prequest.requested_by.id prequest.id %}">View Detail</a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <nav aria-label="Page navigation">
                            <p>Showing {{shipments.count}} of {{page_obj.paginator.count}} data</p>
                            <ul class="pagination justify-content-end">

                                <li class="page-item {% if page_obj.has_previous %}{% else %}disabled{% endif %}">
                                    <a class="page-link"
                                        href="{% if page_obj.has_previous %}?page={{page_obj.previous_page_number}}{% if request.GET.status %}&status={{request.GET.status}}{% elif request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}"
                                        tabindex="-1">Previous</a>
                                </li>

                                {% for n in page_obj.paginator.page_range %}
                                <li class="page-item {% if page_obj.number == n %}active{% endif %}"><a
                                        class="page-link"
                                        href="{% if page_obj.number == n %}#{% else %}?page={{n}}{% if request.GET.status %}&status={{request.GET.status}}{% elif request.GET.search %}&search={{request.GET.search}}{% endif %}{% endif %}">{{n}}</a>
                                </li>
                                {% endfor %}
                                <li class="page-item {% if page_obj.has_next %}{% else %}disabled{% endif %}">
                                    <a class="page-link"
                                        href="{% if page_obj.has_next %}?page={{page_obj.next_page_number}}{% if request.GET.status %}&status={{request.GET.status}}{% elif request.GET.search %}&search={{request.GET.search}}{% endif %}{% else %}#{% endif %}">Next</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js %}

{% endblock %}

templates/logisticstemplates/payment/logisticscustomerpaymentrequestdetail.html
{% extends 'logisticstemplates/logisticsbase.html' %}
{% load static%}
{% load humanize %}

{% block title %}Payment Request Detail{% endblock %}

{% block logisticscustomerpaymentrequests %}active{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<section class="users-list-wrapper">
    <div class="users-list-filter px-1">
        <div class="row border border-light rounded py-2 mb-2">
            <div class="col-md-2">
                <h6 class="text-center">Requested By</h6><hr>
                <h6 class="text-center">{{payment_request.logistics_customer}}</h6>
            </div>
            <div class="col-md-2">
                <h6 class="text-center">Requested on</h6><hr>
                <h6 class="text-center">{{payment_request.created_at}}</h6>
            </div>
            <div class="col-md-2">
                <h6 class="text-center">Requested Amount</h6><hr>
                <h6 class="text-center">Rs. {{payment_request.request_amount|intcomma}}/-</h6>
            </div>
            <div class="col-md-2">
                <h6 class="text-center">Receiver Account</h6><hr>
                <h6 class="text-center">{{payment_request.preferred_receiving_account}}</h6>
            </div>
            <div class="col-md-2">
                <h6 class="text-center">Payment Status</h6><hr>
                <h6 class="text-center">
                    {% if payment_request.is_settled %}
                    <span class="badge badge-success font-weight-bold">Already Settled</span>
                    <p>Settled on: {{payment_request.settled_date}}</p>
                    {% else %}
                    <span class="badge badge-danger font-weight-bold">Not Settled</span>
                    <br>
                    <a href="" id="proceed-to-pay">Proceed to Pay</a>
                    {% endif %}
                </h6>
            </div>
            <div class="col-md-12 border p-1">
                <h6 class="text-danger">Message: {{payment_request.message}}</h6>
            </div>
        </div>
    </div>
    {% if completed_shipments %}
    <div class="users-list-table">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <h4 class="font-weight-bold text-danger">*** IMPORTANT ***</h4>
                            <p class="text-danger">More Shipments are completed</p>
                        </div>
                        <div class="col-md-6">
                            <h5>Current Balance: <span class="font-weight-bold">Rs. {{current_balance|intcomma}}/-</span></h5>
                            <h5>Total Shipments Completed: <span class="font-weight-bold">{{completed_shipments}} Shipments</span></h5>
                        </div>
                        <div class="col-md-3">
                            <a href="" id="include-shipments" class="btn btn-info">Include in Payment</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="users-list-table">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <h6>Included Shipments (Completed)</h5>
                        </div>
                        <div class="col-md-3">
                            <form action="">
                                <input type="search" name="search" class="form-control"
                                    placeholder="Type keyword & press Enter">
                            </form>
                        </div>
                    </div>
                    <!-- datatable start -->
                    <div class="table-responsive mt-1">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Shipment</th>
                                    <th>Shipment Status</th>
                                    <th>COD Value</th>
                                    <th>Service Charge</th>
                                    <th>Net Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for shipment in payment_request.shipments.all %}
                                <tr>
                                    <td><a href="">{{shipment.tracking_code}}</a></td>
                                    <td>
                                        {% if shipment.shipment_status != "Shipment Returned to the Sender" %}
                                        <span class="badge badge-success">
                                            {{shipment.shipment_status}}
                                        </span>
                                        {% else %}
                                        <span class="badge badge-danger">
                                            {{shipment.shipment_status}}
                                        </span>
                                        {% endif %}
                                    </td>
                                    <td>{{shipment.cod_value}}</td>
                                    <td>{{shipment.get_service_charge.0}}</td>
                                    <td>{{shipment.get_service_charge.1}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade text-left" id="payment-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel33"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <label class="modal-title text-text-bold-600" id="myModalLabel33">You are going to Enter payment Record</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'lmsapp:logisticscustomerpaymentrequestpay' payment_request.id %}" method="POST" id="cpa-form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body">
                    {{customer_payment_form.as_p}}
                </div>
                <div class="modal-footer">
                    <input type="reset" class="btn btn-outline-secondary btn-lg" data-dismiss="modal" value="close">
                    <input type="submit" class="btn btn-outline-primary btn-lg" value="Save Information">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    var ptp = document.getElementById("proceed-to-pay")
    ptp.addEventListener("click", function (e){
        e.preventDefault();
        $('#payment-form').modal('show')
        
    })

    $("#include-shipments").on("click", function (e){
        e.preventDefault();
        Swal.fire({
            title: "Include newly completed Shipments to COD Request?",
            type: "info",
            showCancelButton: !0,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Yes, Make Changes!",
            confirmButtonClass: "btn btn-info",
            cancelButtonClass: "btn btn-danger ml-1",
            buttonsStyling: !1,
        }).then(function (t) {
            if (t.value == 1) {
                $.ajax({
                    url: "",
                    method: "post",
                    data: {
                        action: 'include-shipments',
                        csrfmiddlewaretoken: "{{csrf_token}}",
                    },
                    success: function (resp) {
                        location.href = ""
                    }
                })
            }
        })
    })

</script>
{% endblock %}